name: CI

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

defaults:
    run:
        shell: bash

jobs:
    all:
        name: All

        strategy:
            matrix:
                os:
                    - macos-latest
                    - ubuntu-latest
                    - windows-latest

        runs-on: ${{matrix.os}}

        steps:
            - uses: actions/checkout@v3

            - name: Setup macOS/linux
              if: ${{ matrix.os != 'windows-latest' }}
              run: ./setup.sh

            - name: Setup windows
              if: ${{ matrix.os == 'windows-latest' }}
              shell: pwsh
              run: ./setup.ps1

            - name: Install dependencies
              run: npm ci

            - name: Check formatting
              if: ${{ matrix.os != 'windows-latest' }}
              run: npm run format-check

            - name: Package
              run: npm run package
              timeout-minutes: 30

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: ${{ matrix.os }}-binary
                  path: out
